### PR TITLE
Added Laravel 11 Support

### PR DESCRIPTION
**Pull request by arif98741**

### CODE REVIEW

**Comment by bpocallaghan** [comment]
Thank you very much for the PR !

**Comment by arif98741** [comment]
Feeling great after you accepting the PR 🔥

**Comment by bpocallaghan** [comment]
Hahaha - Glad you like it!!
Please do shout if its not working or notice anything funky. 
I might do some upgrades to support Livewire 3 and some minor changes in the near future!

Thanks again - and I am happy this is helping someone else 😄

**Comment by arif98741** [comment]
Of  course, I will try to inform if I find any issue

**Pull request merged**
